### ISSUE TITLE
Support arbitrary alerts from deployment manifest

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/prometheus-boshrelease#100]
As a user of this release, I want to add miscellaneous custom alerts without writing a whole new bosh release. Instead, it would be useful to configure arbitrary alerts like this:

```yaml
...
properties:
  prometheus:
    custom_rules:
    - (( file "path/to/some/rules" ))
    - (( file "path/to/different/rules" ))
...
```

The release would then write the contents of `prometheus.custom_rules` to a file and add the file path to `rule_files`. If that makes sense, we'd be happy to send a patch. WDYT @frodenas ?

cc @cnelson
