### ISSUE TITLE
Split off dashboards and alerts for customization?

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry-community/prometheus-boshrelease#65]
@frodenas @mkuratczyk what do you think about splitting off dashboards and alerts so its easier to customize them? Do you have other ideas on how to do it?

Here is a sample of what it could look like: https://github.com/dlapiduz/prometheus-custom-boshrelease/

**Comment by frodenas** [comment]
@dlapiduz One of the reasons I decoupled the dashboards and alerts from the `grafana` and `prometheus` jobs into their own packages and jobs was to enable people to create/modify their own custom dashboards and alerts. So for example, if you want to replace the actual `cloudfoundry` dashboards, or even override only some of them, you can create your own release with your custom dashboards, collocate it with this release (avoiding using the same job & packages names) and then at the manifest, specifying what dashboards you want to use. An example:

```
instance_groups:
  - name: grafana
    jobs:
      - name: grafana
        release: prometheus
      - name: cloudfoundry_dashboards
        release: prometheus
      - name: custom_cloudfoundry_dashboards
        release: custom
    properties:
      grafana:
        dashboards:
          json:
            enabled: true
        prometheus:
          dashboard_files:
            - /var/vcap/packages/cloudfoundry_dashboards/cf_cc.json
            - /var/vcap/packages/custom_cloudfoundry_dashboards/custom_cf_cc.json
```

Does the above method solves your use case?
