### ISSUE TITLE
grafana dashboard error

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/prometheus-boshrelease#78]
Hello, hit his problem since 15.0.0 (reproduced on 17.0.0 and latest 17.0.2)

Grafana post starts fails with a strange file 

```
Updating dashboard /var/vcap/jobs/cloudfoundry_dashboards/prometheus_cf_exporter.json at Wed Jun  7 10:52:23 UTC 2017
Validating /var/vcap/store/grafana/dashboards//prometheus_cf_exporter.json
Updating dashboard /var/vcap/jobs/cloudfoundry_dashboards/prometheus_firehose_exporter.json at Wed Jun  7 10:52:23 UTC 2017
Validating /var/vcap/store/grafana/dashboards//prometheus_firehose_exporter.json
Updating dashboard agent.cert at Wed Jun  7 10:52:23 UTC 2017
Validating /var/vcap/store/grafana/dashboards//agent.cert
parse error: Invalid numeric literal at line 1, column 11
```
This file is present in /var/vcap/store, dont know where it comes from.

```
grafana/47c0244a-3c59-4837-8602-4b619ef29c60:/var/vcap/store/grafana/dashboards# pwd                                                                       
/var/vcap/store/grafana/dashboards                                                                                                                         
grafana/47c0244a-3c59-4837-8602-4b619ef29c60:/var/vcap/store/grafana/dashboards# ls -lrt                                                                   
total 860                                                                                                                                                  
-rw-r--r-- 1 root root  6687 Jun  7 10:52 bosh_deployments.json                                                                                            
-rw-r--r-- 1 root root 35055 Jun  7 10:52 bosh_jobs.json                                                                                                   
-rw-r--r-- 1 root root 35046 Jun  7 10:52 bosh_overview.json                                                                                               
-rw-r--r-- 1 root root 15181 Jun  7 10:52 bosh_processes.json                                                                                              
-rw-r--r-- 1 root root 28081 Jun  7 10:52 prometheus_bosh_exporter.json
-rw-r--r-- 1 root root 11501 Jun  7 10:52 prometheus_bosh_tsdb_exporter.json
-rw-r--r-- 1 root root 16435 Jun  7 10:52 cf_apps_events.json
-rw-r--r-- 1 root root 13365 Jun  7 10:52 cf_apps_latency.json
-rw-r--r-- 1 root root 36548 Jun  7 10:52 cf_apps_requests.json
-rw-r--r-- 1 root root 20817 Jun  7 10:52 cf_apps_system.json
-rw-r--r-- 1 root root 19154 Jun  7 10:52 cf_bbs.json
-rw-r--r-- 1 root root 21344 Jun  7 10:52 cf_cc.json
-rw-r--r-- 1 root root 20338 Jun  7 10:52 cf_cells_capacity.json
-rw-r--r-- 1 root root 25104 Jun  7 10:52 cf_component_metrics.json
-rw-r--r-- 1 root root 13976 Jun  7 10:52 cf_diego_auctions.json
-rw-r--r-- 1 root root 11125 Jun  7 10:52 cf_diego_health.json
-rw-r--r-- 1 root root 21552 Jun  7 10:52 cf_doppler_server.json
-rw-r--r-- 1 root root 26061 Jun  7 10:52 cf_etcd.json
-rw-r--r-- 1 root root 22500 Jun  7 10:52 cf_etcd_operations.json
-rw-r--r-- 1 root root 11880 Jun  7 10:52 cf_garden_linux.json
-rw-r--r-- 1 root root 78176 Jun  7 10:52 cf_kpis.json
-rw-r--r-- 1 root root 16062 Jun  7 10:52 cf_lrps_tasks.json
-rw-r--r-- 1 root root 15427 Jun  7 10:52 cf_metron_agent.json
-rw-r--r-- 1 root root 13902 Jun  7 10:52 cf_metron_agent_doppler.json
-rw-r--r-- 1 root root 10589 Jun  7 10:52 cf_organization_memory_quotas.json
-rw-r--r-- 1 root root 15680 Jun  7 10:52 cf_organization_summary.json
-rw-r--r-- 1 root root 11204 Jun  7 10:52 cf_route_emitter.json
-rw-r--r-- 1 root root 27468 Jun  7 10:52 cf_router.json
-rw-r--r-- 1 root root 22637 Jun  7 10:52 cf_space_summary.json
-rw-r--r-- 1 root root 47125 Jun  7 10:52 cf_summary.json
-rw-r--r-- 1 root root 22052 Jun  7 10:52 cf_uaa.json
-rw-r--r-- 1 root root 65631 Jun  7 10:52 prometheus_cf_exporter.json
-rw-r--r-- 1 root root 53417 Jun  7 10:52 prometheus_firehose_exporter.json
-rw-r--r-- 1 root root  1058 Jun  7 10:52 agent.cert

```

**Comment by mkuratczyk** [comment]
Hey. It's complaining about file "agent.cert" which quite clearly is not a JSON-formatted Grafana dashboard at all. :)  I don't think that file comes from this bosh release.

**Comment by poblin-orange** [comment]
@mkuratczyk i agree, doesnt seem to be a file of this bosh release :-)
Well i tried to delete it, but it consistently comes back at the same time the grafana poststart runs (see timestemps which confirm).

**Comment by frodenas** [comment]
Can you please check your `grafana.prometheus.dashboard_files` properties? Or the `agent.cert` file is specified there or there is a glob pattern (introduced at [v15.0.0](https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v15.0.0)) pointing to a directory that contains that file.

**Comment by ArthurHlt** [comment]
@poblin-orange you should set the properties `grafana.prometheus.dashboard_files` to `/var/vcap/jobs/*_dashboards/*.json`.
btw @frodenas this can be a default value (or a fixed value) like this you just need to set jobs on the deployment to have dashboard you want, what do you think ?

**Comment by poblin-orange** [comment]
i think i did user the new location. Heres my snippet grafana instance group
```
- name: grafana
  instances: 1
  vm_type: small 
  stemcell: trusty
  azs: [z1]
  networks: [{name: tf-net-exchange}]
  persistent_disk_type: small_disk 
  jobs:
  - name: bosh_dashboards
    release: prometheus
  - name: system_dashboards
    release: prometheus
  - name: cloudfoundry_dashboards
    release: prometheus
  - name: mysql_dashboards
    release: prometheus
    
  - name: kubernetes_dashboards
    release: prometheus
  - name: p_rabbitmq_dashboards
    release: prometheus
  - name: p_redis_dashboards
    release: prometheus
  - name: prometheus_dashboards
    release: prometheus
  - name: rabbitmq_dashboards
    release: prometheus
  - name: redis_dashboards
    release: prometheus
  - name: probe_dashboards
    release: prometheus
  - name: shield_dashboards
    release: prometheus
    
  
  - name: grafana
    release: prometheus
    properties:
      grafana:
        server:
          root_url: (( concat "https://elpaaso-prometheus-grafana." secrets.cloudfoundry.ops_domain "/" ))
          domain: ((grab secrets.cloudfoundry.ops_domain ))
        security:
          admin_password: (( grab secrets.grafana.security.admin_password ))
        dashboards:
          json:
            enabled: true
        prometheus:
          dashboard_files:
            - /var/vcap/jobs/bosh_dashboards/*.json
            - /var/vcap/jobs/cloudfoundry_dashboards/*.json
            - /var/vcap/jobs/consul_dashboards/*.json
            - /var/vcap/jobs/haproxy_dashboards/*.json
            - /var/vcap/jobs/kubernetes_dashboards/*.json
            - /var/vcap/jobs/mysql_dashboards/*.json
            - /var/vcap/jobs/p_rabbitmq_dashboards/*.json
            - /var/vcap/jobs/p_redis_dashboards/*.json
            - /var/vcap/jobs/postgres_dashboards/*.json
            - /var/vcap/jobs/probe_dashboards/*.json
            - /var/vcap/jobs/prometheus_dashboards/*.json
            - /var/vcap/jobs/rabbitmq_dashboards/*.json
            - /var/vcap/jobs/redis_dashboards/*.json
            - /var/vcap/jobs/system_dashboards/*.json
            - /var/vcap/jobs/p_rabbitmq_dashboards/*.json
            - /var/vcap/jobs/shield_dashboards/*.json            
          
        users:
          allow_sign_up: false
        auth:
          disable_login_form: false # set to true when oauth login
          ldap:
            enabled: true
            config: (( file "secrets/grafana.auth.ldap.config.toml" )) 
```
