### ISSUE TITLE
dropping unnecessary property namespacing

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-community/prometheus-boshrelease#9]
it would be nice to drop job name property namespacing to remove some of the repetitiveness. for example:

[`prometheus.evaluation_interval`](https://github.com/cloudfoundry-community/prometheus-boshrelease/blob/master/jobs/prometheus/spec#L31) would become just `evaluation_interval`. 

wdyt? i would be happy to do a PR that applies this to all the jobs.

**Comment by frodenas** [comment]
I personally like the **job namespaced** approach, to me it improves readability and ownership of the properties especially when a user needs to create/update/debug a deployment manifest.

OTOH, I recognize it's a pain for the release dev and might be cumbersome when using ie links. But I rather prefer to make this easier to the users than not the release developer.

**Comment by cppforlife** [comment]
> I personally like the job namespaced approach, to me it improves readability and ownership of the properties

well... i never know which property is used by which job, because there was no enforcement from bosh. we had/have jobs that were reading other jobs namespace (nats.* for example). hence we've added job level properties (http://bosh.io/docs/manifest-v2.html#instance-groups). for example:

```
instance_groups:
- name: prometheus
  instances: 1
  jobs:
  - name: prometheus
    properties:
      scrape_interval: something  # <-- weird if namespaced once more
      ...
```

In the above scenario it's crystal clear (imho) that scrape_interval belongs to prometheus job. Even better Director enforces association and doesnt not allow anyone else to access those properties. Job level properties are not merged with anything as well.
